@baseUrl = https://3vk5t9om0l.execute-api.eu-west-1.amazonaws.com/prod

# @name placeOrder
POST {{baseUrl}}/orders HTTP/1.1
content-type: application/json

{
    "lineItems": [
        {
            "sku": "AAA-00001",
            "quantity": 1,
            "unitPrice": 4.99
        },
        {
            "sku": "AAA-00002",
            "quantity": 2,
            "unitPrice": 12.49
        }
    ]
}

###

@orderId = {{placeOrder.response.body.orderId}}

# @name addLineItemToOrder
POST {{baseUrl}}/orders/{{orderId}}/items HTTP/1.1
content-type: application/json

{
    "sku": "AAA-00003",
    "quantity": 3,
    "unitPrice": 1.29
}

###

# @name getOrder
GET {{baseUrl}}/orders/{{orderId}} HTTP/1.1
content-type: application/json

###

# @name approveOrder
POST {{baseUrl}}/orders/{{orderId}}/approve HTTP/1.1
content-type: application/json

###

# @name paymentReceived
POST https://hmigg3okfdaosq2k7svbasymwu0uknut.lambda-url.eu-west-1.on.aws/ HTTP/1.1
content-type: application/json

{
    "aggregateId": "12345",
    "type": "PaymentReceived",
    "orderId": "{{orderId}}",
    "amount": 33.84
}